/////////////////////////////////////////////////////////////////////////////
//      
//      File      : qtc_hs_QGLWidget.h
//      Copyright : (c) David Harley 2010
//      Project   : qtHaskell
//      Version   : 1.1.4
//      Modified  : 2010-09-02 17:02:42
//      
//      Warning   : this file is machine generated - do not modify.
//      
/////////////////////////////////////////////////////////////////////////////

void* qtc_QGLWidget();
void* qtc_QGLWidget1(void*);
void* qtc_QGLWidget2(void*);
void* qtc_QGLWidget3(void*);
void* qtc_QGLWidget4(void*,void*);
void* qtc_QGLWidget5(void*,void*);
void* qtc_QGLWidget6(void*,void*,long);
void* qtc_QGLWidget7(void*,void*,void*,long);
void* qtc_QGLWidget8(void*,void*,void*,long);
int qtc_QGLWidget_autoBufferSwap(void*);
unsigned int qtc_QGLWidget_bindTexture(void*,void*);
unsigned int qtc_QGLWidget_bindTexture1(void*,void*);
unsigned int qtc_QGLWidget_bindTexture2(void*,void*);
unsigned int qtc_QGLWidget_bindTexture3(void*,void*,int);
unsigned int qtc_QGLWidget_bindTexture4(void*,void*,int);
unsigned int qtc_QGLWidget_bindTexture5(void*,void*,int,int);
unsigned int qtc_QGLWidget_bindTexture6(void*,void*,int,int);
void* qtc_QGLWidget_colormap(void*);
void* qtc_QGLWidget_context(void*);
void* qtc_QGLWidget_convertToGLFormat(void*);
void qtc_QGLWidget_deleteTexture(void*,unsigned int);
void qtc_QGLWidget_doneCurrent(void*);
int qtc_QGLWidget_doubleBuffer(void*);
int qtc_QGLWidget_event(void*,void*);
int qtc_QGLWidget_fontDisplayListBase(void*,void*);
int qtc_QGLWidget_fontDisplayListBase1(void*,void*,int);
void* qtc_QGLWidget_format(void*);
void qtc_QGLWidget_glDraw(void*);
void qtc_QGLWidget_glInit(void*);
void* qtc_QGLWidget_grabFrameBuffer(void*);
void* qtc_QGLWidget_grabFrameBuffer1(void*,int);
void qtc_QGLWidget_initializeGL(void*);
void qtc_QGLWidget_initializeOverlayGL(void*);
int qtc_QGLWidget_isSharing(void*);
int qtc_QGLWidget_isValid(void*);
void qtc_QGLWidget_makeCurrent(void*);
void qtc_QGLWidget_makeOverlayCurrent(void*);
void* qtc_QGLWidget_overlayContext(void*);
void* qtc_QGLWidget_paintEngine(void*);
void qtc_QGLWidget_paintEvent(void*,void*);
void qtc_QGLWidget_paintGL(void*);
void qtc_QGLWidget_paintOverlayGL(void*);
void qtc_QGLWidget_qglClearColor(void*,void*);
void qtc_QGLWidget_qglColor(void*,void*);
void* qtc_QGLWidget_renderPixmap(void*);
void* qtc_QGLWidget_renderPixmap1(void*,int);
void* qtc_QGLWidget_renderPixmap2(void*,int,int);
void* qtc_QGLWidget_renderPixmap3(void*,int,int,int);
void qtc_QGLWidget_renderText(void*,int,int,void*);
void qtc_QGLWidget_renderText1(void*,int,int,void*,void*);
void qtc_QGLWidget_renderText2(void*,double,double,double,void*);
void qtc_QGLWidget_renderText3(void*,double,double,double,void*,void*);
void qtc_QGLWidget_renderText4(void*,int,int,void*,void*,int);
void qtc_QGLWidget_renderText5(void*,double,double,double,void*,void*,int);
void qtc_QGLWidget_resizeEvent(void*,void*);
void qtc_QGLWidget_resizeGL(void*,int,int);
void qtc_QGLWidget_resizeOverlayGL(void*,int,int);
void qtc_QGLWidget_setAutoBufferSwap(void*,int);
void qtc_QGLWidget_setColormap(void*,void*);
void qtc_QGLWidget_setContext(void*,void*);
void qtc_QGLWidget_setContext1(void*,void*,void*);
void qtc_QGLWidget_setContext2(void*,void*,void*,int);
void qtc_QGLWidget_setFormat(void*,void*);
void qtc_QGLWidget_setMouseTracking(void*,int);
void qtc_QGLWidget_swapBuffers(void*);
void qtc_QGLWidget_updateGL(void*);
void qtc_QGLWidget_updateOverlayGL(void*);
void qtc_QGLWidget_finalizer(void*);
void* qtc_QGLWidget_getFinalizer();
void qtc_QGLWidget_delete(void*);
void qtc_QGLWidget_deleteLater(void*);
void qtc_QGLWidget_actionEvent(void*,void*);
void qtc_QGLWidget_addAction(void*,void*);
void qtc_QGLWidget_changeEvent(void*,void*);
void qtc_QGLWidget_closeEvent(void*,void*);
void qtc_QGLWidget_contextMenuEvent(void*,void*);
void qtc_QGLWidget_create(void*);
void qtc_QGLWidget_create1(void*,void*);
void qtc_QGLWidget_create2(void*,void*,int);
void qtc_QGLWidget_create3(void*,void*,int,int);
void qtc_QGLWidget_destroy(void*);
void qtc_QGLWidget_destroy1(void*,int);
void qtc_QGLWidget_destroy2(void*,int,int);
int qtc_QGLWidget_devType(void*);
void qtc_QGLWidget_dragEnterEvent(void*,void*);
void qtc_QGLWidget_dragLeaveEvent(void*,void*);
void qtc_QGLWidget_dragMoveEvent(void*,void*);
void qtc_QGLWidget_dropEvent(void*,void*);
void qtc_QGLWidget_enabledChange(void*,int);
void qtc_QGLWidget_enterEvent(void*,void*);
void qtc_QGLWidget_focusInEvent(void*,void*);
int qtc_QGLWidget_focusNextChild(void*);
int qtc_QGLWidget_focusNextPrevChild(void*,int);
void qtc_QGLWidget_focusOutEvent(void*,void*);
int qtc_QGLWidget_focusPreviousChild(void*);
void qtc_QGLWidget_fontChange(void*,void*);
int qtc_QGLWidget_heightForWidth(void*,int);
void qtc_QGLWidget_hideEvent(void*,void*);
void qtc_QGLWidget_inputMethodEvent(void*,void*);
void* qtc_QGLWidget_inputMethodQuery(void*,long);
void qtc_QGLWidget_keyPressEvent(void*,void*);
void qtc_QGLWidget_keyReleaseEvent(void*,void*);
void qtc_QGLWidget_languageChange(void*);
void qtc_QGLWidget_leaveEvent(void*,void*);
int qtc_QGLWidget_metric(void*,long);
void* qtc_QGLWidget_minimumSizeHint(void*);
void* qtc_QGLWidget_minimumSizeHint_qth(void*,int*,int*);
void qtc_QGLWidget_mouseDoubleClickEvent(void*,void*);
void qtc_QGLWidget_mouseMoveEvent(void*,void*);
void qtc_QGLWidget_mousePressEvent(void*,void*);
void qtc_QGLWidget_mouseReleaseEvent(void*,void*);
void qtc_QGLWidget_move(void*,void*);
void qtc_QGLWidget_move_qth(void*);
void qtc_QGLWidget_move1(void*,int,int);
void qtc_QGLWidget_moveEvent(void*,void*);
void qtc_QGLWidget_paletteChange(void*,void*);
void qtc_QGLWidget_repaint(void*);
void qtc_QGLWidget_repaint1(void*,void*);
void qtc_QGLWidget_repaint2(void*,int,int,int,int);
void qtc_QGLWidget_resetInputContext(void*);
void qtc_QGLWidget_resize(void*,void*);
void qtc_QGLWidget_resize_qth(void*);
void qtc_QGLWidget_resize1(void*,int,int);
void qtc_QGLWidget_setGeometry(void*,void*);
void qtc_QGLWidget_setGeometry_qth(void*);
void qtc_QGLWidget_setGeometry1(void*,int,int,int,int);
void qtc_QGLWidget_setVisible(void*,int);
void qtc_QGLWidget_showEvent(void*,void*);
void* qtc_QGLWidget_sizeHint(void*);
void* qtc_QGLWidget_sizeHint_qth(void*,int*,int*);
void qtc_QGLWidget_tabletEvent(void*,void*);
void qtc_QGLWidget_updateMicroFocus(void*);
void qtc_QGLWidget_wheelEvent(void*,void*);
void qtc_QGLWidget_windowActivationChange(void*,int);
void qtc_QGLWidget_childEvent(void*,void*);
void qtc_QGLWidget_connectNotify(void*,void*);
void qtc_QGLWidget_customEvent(void*,void*);
void qtc_QGLWidget_disconnectNotify(void*,void*);
int qtc_QGLWidget_eventFilter(void*,void*,void*);
int qtc_QGLWidget_receivers(void*,void*);
void* qtc_QGLWidget_sender(void*);
void qtc_QGLWidget_timerEvent(void*,void*);
