/////////////////////////////////////////////////////////////////////////////
//      
//      File      : qtc_hs_QGraphicsScene.h
//      Copyright : (c) David Harley 2010
//      Project   : qtHaskell
//      Version   : 1.1.4
//      Modified  : 2010-09-02 17:02:39
//      
//      Warning   : this file is machine generated - do not modify.
//      
/////////////////////////////////////////////////////////////////////////////

void* qtc_QGraphicsScene();
void* qtc_QGraphicsScene1(void*);
void* qtc_QGraphicsScene2(double, double, double, double);
void* qtc_QGraphicsScene3(void*);
void* qtc_QGraphicsScene4(void*,void*);
void* qtc_QGraphicsScene5(double, double, double, double,void*);
void* qtc_QGraphicsScene6(double,double,double,double);
void* qtc_QGraphicsScene7(double,double,double,double,void*);
void* qtc_QGraphicsScene_addEllipse(void*,void*);
void* qtc_QGraphicsScene_addEllipse_qth(void*);
void* qtc_QGraphicsScene_addEllipse1(void*,void*,void*);
void* qtc_QGraphicsScene_addEllipse1_qth(void*,void*);
void* qtc_QGraphicsScene_addEllipse2(void*,void*,void*,void*);
void* qtc_QGraphicsScene_addEllipse2_qth(void*,void*,void*);
void* qtc_QGraphicsScene_addEllipse3(void*,double,double,double,double);
void* qtc_QGraphicsScene_addEllipse4(void*,double,double,double,double,void*);
void* qtc_QGraphicsScene_addEllipse5(void*,double,double,double,double,void*,void*);
void qtc_QGraphicsScene_addItem(void*,void*);
void qtc_QGraphicsScene_addItem_graphicstextitem(void*,void*);
void* qtc_QGraphicsScene_addLine(void*,void*);
void* qtc_QGraphicsScene_addLine_qth(void*);
void* qtc_QGraphicsScene_addLine1(void*,void*,void*);
void* qtc_QGraphicsScene_addLine1_qth(void*,void*);
void* qtc_QGraphicsScene_addLine2(void*,double,double,double,double);
void* qtc_QGraphicsScene_addLine3(void*,double,double,double,double,void*);
void* qtc_QGraphicsScene_addPath(void*,void*);
void* qtc_QGraphicsScene_addPath1(void*,void*,void*);
void* qtc_QGraphicsScene_addPath2(void*,void*,void*,void*);
void* qtc_QGraphicsScene_addPixmap(void*,void*);
void* qtc_QGraphicsScene_addPolygon(void*,void*);
void* qtc_QGraphicsScene_addPolygon1(void*,void*,void*);
void* qtc_QGraphicsScene_addPolygon2(void*,void*,void*,void*);
void* qtc_QGraphicsScene_addRect(void*,void*);
void* qtc_QGraphicsScene_addRect_qth(void*);
void* qtc_QGraphicsScene_addRect1(void*,void*,void*);
void* qtc_QGraphicsScene_addRect1_qth(void*,void*);
void* qtc_QGraphicsScene_addRect2(void*,void*,void*,void*);
void* qtc_QGraphicsScene_addRect2_qth(void*,void*,void*);
void* qtc_QGraphicsScene_addRect3(void*,double,double,double,double);
void* qtc_QGraphicsScene_addRect4(void*,double,double,double,double,void*);
void* qtc_QGraphicsScene_addRect5(void*,double,double,double,double,void*,void*);
void* qtc_QGraphicsScene_addSimpleText(void*,void*);
void* qtc_QGraphicsScene_addSimpleText1(void*,void*,void*);
void* qtc_QGraphicsScene_addText(void*,void*);
void* qtc_QGraphicsScene_addText1(void*,void*,void*);
void qtc_QGraphicsScene_advance(void*);
void* qtc_QGraphicsScene_backgroundBrush(void*);
int qtc_QGraphicsScene_bspTreeDepth(void*);
void qtc_QGraphicsScene_clearFocus(void*);
void qtc_QGraphicsScene_clearSelection(void*);
int qtc_QGraphicsScene_collidingItems(void*,void*,void*);
int qtc_QGraphicsScene_collidingItems_graphicstextitem(void*,void*,void*);
int qtc_QGraphicsScene_collidingItems1(void*,void*,long,void*);
int qtc_QGraphicsScene_collidingItems1_graphicstextitem(void*,void*,long,void*);
void qtc_QGraphicsScene_contextMenuEvent(void*,void*);
void qtc_QGraphicsScene_destroyItemGroup(void*,void*);
void qtc_QGraphicsScene_dragEnterEvent(void*,void*);
void qtc_QGraphicsScene_dragLeaveEvent(void*,void*);
void qtc_QGraphicsScene_dragMoveEvent(void*,void*);
void qtc_QGraphicsScene_drawBackground(void*,void*,void*);
void qtc_QGraphicsScene_drawBackground_qth(void*,void*, double, double, double, double);
void qtc_QGraphicsScene_drawForeground(void*,void*,void*);
void qtc_QGraphicsScene_drawForeground_qth(void*,void*, double, double, double, double);
void qtc_QGraphicsScene_drawItems(void*,void*,int,int,QGraphicsItem**,int,void*);
void qtc_QGraphicsScene_drawItems1(void*,void*,int,int,QGraphicsItem**,int,void*,void*);
void qtc_QGraphicsScene_dropEvent(void*,void*);
int qtc_QGraphicsScene_event(void*,void*);
void qtc_QGraphicsScene_focusInEvent(void*,void*);
void* qtc_QGraphicsScene_focusItem(void*);
void qtc_QGraphicsScene_focusOutEvent(void*,void*);
void* qtc_QGraphicsScene_foregroundBrush(void*);
int qtc_QGraphicsScene_hasFocus(void*);
double qtc_QGraphicsScene_height(void*);
void qtc_QGraphicsScene_helpEvent(void*,void*);
void qtc_QGraphicsScene_inputMethodEvent(void*,void*);
void* qtc_QGraphicsScene_inputMethodQuery(void*,long);
void qtc_QGraphicsScene_invalidate(void*);
void qtc_QGraphicsScene_invalidate1(void*,void*);
void qtc_QGraphicsScene_invalidate1_qth(void*);
void qtc_QGraphicsScene_invalidate2(void*,void*,long);
void qtc_QGraphicsScene_invalidate2_qth(void*,long);
void qtc_QGraphicsScene_invalidate3(void*,double,double,double,double);
void qtc_QGraphicsScene_invalidate4(void*,double,double,double,double,long);
void* qtc_QGraphicsScene_itemAt(void*,void*);
void* qtc_QGraphicsScene_itemAt_qth(void*);
void* qtc_QGraphicsScene_itemAt1(void*,double,double);
long qtc_QGraphicsScene_itemIndexMethod(void*);
int qtc_QGraphicsScene_items(void*,void*);
int qtc_QGraphicsScene_items1(void*,void*,void*);
int qtc_QGraphicsScene_items1_qth(void*,void*);
int qtc_QGraphicsScene_items2(void*,void*,void*);
int qtc_QGraphicsScene_items3(void*,void*,void*);
int qtc_QGraphicsScene_items3_qth(void*,void*);
int qtc_QGraphicsScene_items4(void*,void*,void*);
int qtc_QGraphicsScene_items5(void*,void*,long,void*);
int qtc_QGraphicsScene_items6(void*,void*,long,void*);
int qtc_QGraphicsScene_items7(void*,void*,long,void*);
int qtc_QGraphicsScene_items7_qth(void*,long,void*);
int qtc_QGraphicsScene_items8(void*,double,double,double,double,void*);
int qtc_QGraphicsScene_items9(void*,double,double,double,double,long,void*);
void* qtc_QGraphicsScene_itemsBoundingRect(void*);
void* qtc_QGraphicsScene_itemsBoundingRect_qth(void*,double*,double*,double*,double*);
void qtc_QGraphicsScene_keyPressEvent(void*,void*);
void qtc_QGraphicsScene_keyReleaseEvent(void*,void*);
void qtc_QGraphicsScene_mouseDoubleClickEvent(void*,void*);
void* qtc_QGraphicsScene_mouseGrabberItem(void*);
void qtc_QGraphicsScene_mouseMoveEvent(void*,void*);
void qtc_QGraphicsScene_mousePressEvent(void*,void*);
void qtc_QGraphicsScene_mouseReleaseEvent(void*,void*);
void qtc_QGraphicsScene_removeItem(void*,void*);
void qtc_QGraphicsScene_removeItem_graphicstextitem(void*,void*);
void qtc_QGraphicsScene_render(void*,void*);
void qtc_QGraphicsScene_render1(void*,void*,void*);
void qtc_QGraphicsScene_render1_qth(void*,void*);
void qtc_QGraphicsScene_render2(void*,void*,void*,void*);
void qtc_QGraphicsScene_render2_qth(void*,void*);
void qtc_QGraphicsScene_render3(void*,void*,void*,void*,long);
void qtc_QGraphicsScene_render3_qth(void*,void*,long);
void* qtc_QGraphicsScene_sceneRect(void*);
void* qtc_QGraphicsScene_sceneRect_qth(void*,double*,double*,double*,double*);
int qtc_QGraphicsScene_selectedItems(void*,void*);
void* qtc_QGraphicsScene_selectionArea(void*);
void qtc_QGraphicsScene_setBackgroundBrush(void*,void*);
void qtc_QGraphicsScene_setBspTreeDepth(void*,int);
void qtc_QGraphicsScene_setFocus(void*);
void qtc_QGraphicsScene_setFocus1(void*,long);
void qtc_QGraphicsScene_setFocusItem(void*,void*);
void qtc_QGraphicsScene_setFocusItem_graphicstextitem(void*,void*);
void qtc_QGraphicsScene_setFocusItem1(void*,void*,long);
void qtc_QGraphicsScene_setFocusItem1_graphicstextitem(void*,void*,long);
void qtc_QGraphicsScene_setForegroundBrush(void*,void*);
void qtc_QGraphicsScene_setItemIndexMethod(void*,long);
void qtc_QGraphicsScene_setSceneRect(void*,void*);
void qtc_QGraphicsScene_setSceneRect_qth(void*);
void qtc_QGraphicsScene_setSceneRect1(void*,double,double,double,double);
void qtc_QGraphicsScene_setSelectionArea(void*,void*);
void qtc_QGraphicsScene_setSelectionArea1(void*,void*,long);
void qtc_QGraphicsScene_update(void*);
void qtc_QGraphicsScene_update1(void*,void*);
void qtc_QGraphicsScene_update1_qth(void*);
void qtc_QGraphicsScene_update2(void*,double,double,double,double);
int qtc_QGraphicsScene_views(void*,void*);
void qtc_QGraphicsScene_wheelEvent(void*,void*);
double qtc_QGraphicsScene_width(void*);
void qtc_QGraphicsScene_finalizer(void*);
void* qtc_QGraphicsScene_getFinalizer();
void qtc_QGraphicsScene_delete(void*);
void qtc_QGraphicsScene_deleteLater(void*);
void qtc_QGraphicsScene_childEvent(void*,void*);
void qtc_QGraphicsScene_connectNotify(void*,void*);
void qtc_QGraphicsScene_customEvent(void*,void*);
void qtc_QGraphicsScene_disconnectNotify(void*,void*);
int qtc_QGraphicsScene_eventFilter(void*,void*,void*);
int qtc_QGraphicsScene_receivers(void*,void*);
void* qtc_QGraphicsScene_sender(void*);
void qtc_QGraphicsScene_timerEvent(void*,void*);
